MyPhamStore/Models/MyPham.cs
namespace MyPhamStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;
    using System.Web;

    [Table("MyPham")]
    public partial class MyPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MyPham()
        {
            OrderDetails = new HashSet<OrderDetail>();
        }

        public int Id { get; set; }

        [Required]
        [StringLength(150)]
        public string Name { get; set; }

        public decimal? Price { get; set; }

        public string MoTa { get; set; }

        [StringLength(250)]
        public string Image { get; set; }

        [NotMapped]
        public HttpPostedFileBase ImageFile { get; set; }

        public int BrandId { get; set; }

        public int CategoryId { get; set; }

        public virtual Brand Brand { get; set; }

        public virtual Category Category { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}

MyPhamStore/Areas/Admin/Controllers/MyPhamsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyPhamStore.Models;

namespace MyPhamStore.Areas.Admin.Controllers
{
    public class MyPhamsController : Controller
    {
        private MyPhamModelContext db = new MyPhamModelContext();

        // GET: Admin/MyPhams
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            var myPhams = db.MyPhams.Include(m => m.Brand).Include(m => m.Category);
            return View(myPhams.ToList());
        }
        [Authorize(Roles = "Admin")]
        // GET: Admin/MyPhams/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MyPham myPham = db.MyPhams.Find(id);
            if (myPham == null)
            {
                return HttpNotFound();
            }
            return View(myPham);
        }
        [Authorize(Roles = "Admin")]
        // GET: Admin/MyPhams/Create
        public ActionResult Create()
        {
            ViewBag.BrandId = new SelectList(db.Brands, "BrandId", "BrandName");
            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "CategoryName");
            return View();
        }

        // POST: Admin/MyPhams/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(MyPham myPham)
        {
            var context = new MyPhamModelContext();
            if (ModelState.IsValid)
            {
                if (myPham.ImageFile != null && myPham.ImageFile.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(myPham.ImageFile.FileName);
                    var filePath = Path.Combine(Server.MapPath("~/Content/ImageProducts/MyPham"), fileName);
                    myPham.ImageFile.SaveAs(filePath);
                    myPham.Image = "" + fileName;
                }
                context.MyPhams.Add(myPham);
                context.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.BrandId = new SelectList(db.Brands, "BrandId", "BrandName", myPham.BrandId);
            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "CategoryName", myPham.CategoryId);
            return View(myPham);
        }
        [Authorize(Roles = "Admin")]
        // GET: Admin/MyPhams/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MyPham myPham = db.MyPhams.Find(id);
            if (myPham == null)
            {
                return HttpNotFound();
            }
            ViewBag.BrandId = new SelectList(db.Brands, "BrandId", "BrandName", myPham.BrandId);
            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "CategoryName", myPham.CategoryId);
            return View(myPham);
        }

        // POST: Admin/MyPhams/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(MyPham myPham)
        {
            if (ModelState.IsValid)
            {
                if (myPham.ImageFile != null && myPham.ImageFile.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(myPham.ImageFile.FileName);
                    var filePath = Path.Combine(Server.MapPath("~/Content/ImageProducts/MyPham"), fileName);
                    myPham.ImageFile.SaveAs(filePath);
                    myPham.Image = fileName;
                }

                db.Entry(myPham).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.BrandId = new SelectList(db.Brands, "BrandId", "BrandName", myPham.BrandId);
            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "CategoryName", myPham.CategoryId);
            return View(myPham);
        }
        [Authorize(Roles = "Admin")]
        // GET: Admin/MyPhams/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MyPham myPham = db.MyPhams.Find(id);
            if (myPham == null)
            {
                return HttpNotFound();
            }
            return View(myPham);
        }

        // POST: Admin/MyPhams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            MyPham myPham = db.MyPhams.Find(id);
            db.MyPhams.Remove(myPham);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MyPhamStore/Controllers/MyPhamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyPhamStore.Models;
using PagedList;

namespace MyPhamStore.Controllers
{
    public class MyPhamController : Controller
    {
        // GET: MyPham
        //public ActionResult Index()
        //{
        //    var context = new MyPhamModelContext();
        //    return View(context.MyPhams.ToList());
        //}

        public ActionResult Index(int? page, int? categoryId, string searchString)
        {

            var context = new MyPhamModelContext();
            int pageSize = 6;
            int pageIndex = page.HasValue ? page.Value : 1;
            var listProduct = context.MyPhams.ToList();

            // Filter by categoryId, if specified
            if (categoryId.HasValue)
            {
                listProduct = listProduct.Where(p => p.CategoryId == categoryId.Value).ToList();
            }

            // Search by searchString, if specified
            if (!string.IsNullOrEmpty(searchString))
            {
                listProduct = listProduct.Where(p => p.Category.CategoryName.Contains(searchString) || p.Brand.BrandName.Contains(searchString) || p.Name.Contains(searchString)).ToList();
            }

            var result = listProduct.ToPagedList(pageIndex, pageSize);
            return View("Index", result);
        }

        //public ActionResult GetMyPhamCategory(int id)
        //{
        //    var context = new MyPhamModelContext();
        //    return View("Index", context.MyPhams.Where(p => p.CategoryId == id).ToList());
        //}
        public ActionResult GetMyPhamCategory(int id, int? page)
        {
            var context = new MyPhamModelContext();
            var listProduct = context.MyPhams.Where(p => p.CategoryId == id).ToList();

            int pageSize = 10;
            int pageIndex = page.HasValue ? page.Value : 1;
            var result = listProduct.ToPagedList(pageIndex, pageSize);

            return View("Index", result);
        }

        //public ActionResult GetCategory()
        //{
        //    var context = new MyPhamModelContext();
        //    var listCategory = context.Categories.ToList();
        //    return PartialView(listCategory);
        //}
        public ActionResult GetCategory()
        {
            var context = new MyPhamModelContext();
            var listCategory = context.Categories.ToList();
            return PartialView("GetCategory", listCategory);
        }

        public ActionResult GetMyPhamBrand(int id, int? page)
        {
            var context = new MyPhamModelContext();
            var listBrand = context.MyPhams.Where(p => p.BrandId == id).ToList();

            int pageSize = 10;
            int pageIndex = page.HasValue ? page.Value : 1;
            var result = listBrand.ToPagedList(pageIndex, pageSize);

            return View("Index", result);
        }

        //public ActionResult GetMyPhamBrand(int id)
        //{
        //    var context = new MyPhamModelContext();
        //    return View("Index", context.MyPhams.Where(p => p.BrandId == id).ToList());
        //}

        //public ActionResult GetBrand()
        //{
        //    var context = new MyPhamModelContext();
        //    var listBrand = context.Brands.ToList();
        //    return PartialView(listBrand);
        //}
        public ActionResult GetBrand()
        {
            var context = new MyPhamModelContext();
            var listBrand = context.Brands.ToList();
            return PartialView("GetBrand", listBrand);
        }

        public ActionResult Details(int id)
        {
            var context = new MyPhamModelContext();
            var firstMyPham = context.MyPhams.FirstOrDefault(p => p.Id == id);
            if (firstMyPham == null)
                return HttpNotFound("Không tìm thấy mã sản phẩm này!");
            return View(firstMyPham);
        }

        //public ActionResult Search(string searchString)
        //{
        //    var context = new MyPhamModelContext();
        //    var results =
        //        (from m in context.MyPhams
        //         where
        //         m.Brand.BrandName.Contains(searchString)
        //         || m.Category.CategoryName.Contains(searchString)
        //         || m.Name.Contains(searchString)
        //         select m);
        //    if (results.Count() > 0)
        //        return View("Index", results);
        //    return HttpNotFound("TThông tin tìm kiếm không tồn tại, xin cảm ơn");
        //}
        public ActionResult Search(string searchString, int? page)
        {
            var context = new MyPhamModelContext();
            var results = context.MyPhams
                .Where(m => m.Brand.BrandName.Contains(searchString) 
                || m.Category.CategoryName.Contains(searchString) 
                || m.Name.Contains(searchString))
                .OrderBy(p => p.Id)
                .ToPagedList(page ?? 1, 10);

            if (results.Count() > 0)
                return View("Index", results);

            return HttpNotFound("Thông tin tìm kiếm chưa có. Xin cảm ơn");
        }
    }
}

MyPhamStore/Areas/Admin/Views/MyPhams/Create.cshtml
@model MyPhamStore.Models.MyPham

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}



@using (Html.BeginForm("Create", "MyPhams", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>MyPham</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MoTa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MoTa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MoTa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control" } })
                 @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })*@
                <input type="file" name="ImageFile" required class="form-control" accept=".png, .jpg, .jpeg" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BrandId, "BrandId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("BrandId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.BrandId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, "CategoryId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MyPhamStore/Areas/Admin/Views/MyPhams/Delete.cshtml
@model MyPhamStore.Models.MyPham

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}



<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MyPham</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Brand.BrandName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Brand.BrandName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category.CategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.CategoryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MoTa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MoTa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MyPhamStore/Areas/Admin/Views/MyPhams/Details.cshtml
@model MyPhamStore.Models.MyPham

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}



<div>
    <h4>MyPham</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Brand.BrandName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Brand.BrandName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category.CategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.CategoryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MoTa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MoTa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MyPhamStore/Areas/Admin/Views/MyPhams/Edit.cshtml
@model MyPhamStore.Models.MyPham

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}



@using (Html.BeginForm("Edit", "MyPhams", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>MyPham</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MoTa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MoTa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MoTa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })*@
                <input type="file" name="ImageFile" required class="form-control" accept=".png, .jpg, .jpeg" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BrandId, "BrandId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("BrandId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.BrandId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, "CategoryId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MyPhamStore/Areas/Admin/Views/MyPhams/Index.cshtml
@model IEnumerable<MyPhamStore.Models.MyPham>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
    <table>
        <div class="border-bottom " style="height: 75px;">
            @Html.ActionLink("Thêm sản phẩm mới", "Create", "MyPhams", new
               {
                   @class = "btn btn-success p-3 mt-2 float-right mr-2"
               })
        </div>

        <div class="px-2">
            <table class="table table-bordered table-hover table-striped">
                <thead class="table-dark">
                    <tr>
                        <th>Mã thương hiệu</th>
                        <th>Thể Loại Sản Phẩm</th>
                        <th>Tên Sản Phẩm </th>
                        <th>Hình Ảnh </th>
                        <th>Mô Tả Sản Phẩm </th>
                        <th>Giá Tiền </th>
                        <th></th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                        @foreach (var item in Model)
                        {
                    <tr>
                        <td>@item.Brand.BrandName</td>
                        <td>@item.Category.CategoryName</td>
                        <td>@item.Name</td>
                        <td><img src="~/Content/ImageProducts/MyPham/@item.Image" width="50px" alt=""></td>
                        <td>@item.MoTa</td>
                        <td>
                            <p class="new_price" id="product-price-@item.Id"></p>
                            <script>
                                var price = @item.Price;
                                document.getElementById("product-price-@item.Id").innerHTML = formatPrice(price) + ' VNĐ';

                                function formatPrice(price) {
                                    return parseFloat(price).toLocaleString('vi-VN');
                                }
                            </script>
                        </td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", "MyPhams", new { id = item.Id }, new { @class = "btn btn-primary" })                            
                        </td>
                        <td>
                            @Html.ActionLink("Delete", "Delete", "MyPhams", new { id = item.Id }, new { @class = "btn btn-danger", onclick = "return confirm('Are you sure you want to delete this item?');" })

                        </td>
                            
                    </tr>
                        }
                    
                </tbody>
            </table>